/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classes.CadastrarFuncionario;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private int codLogin;
    public Principal(int cod) {
        initComponents();
        codLogin = cod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArquivos = new javax.swing.JMenu();
        jMISair = new javax.swing.JMenuItem();
        jMUsuarios = new javax.swing.JMenu();
        jMIPerfil = new javax.swing.JMenuItem();
        jMIGerenciarUsu = new javax.swing.JMenuItem();
        jMFornecedores = new javax.swing.JMenu();
        jMIGerenciarForne = new javax.swing.JMenuItem();
        jMProdutos = new javax.swing.JMenu();
        jMIGerenciarProd = new javax.swing.JMenuItem();
        jMVendas = new javax.swing.JMenu();
        jMIEfeVenda = new javax.swing.JMenuItem();
        jMRelatorio = new javax.swing.JMenu();
        jMIRelatorioProd = new javax.swing.JMenuItem();
        jMIRelatVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 3, 48)); // NOI18N
        jLabel1.setText("Bem Vindo!");

        jMArquivos.setText("Arquivo");

        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMArquivos.add(jMISair);

        jMenuBar1.add(jMArquivos);

        jMUsuarios.setText("Usuarios");

        jMIPerfil.setText("Perfil");
        jMIPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPerfilActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMIPerfil);

        jMIGerenciarUsu.setText("Gerenciar Usuários");
        jMIGerenciarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciarUsuActionPerformed(evt);
            }
        });
        jMUsuarios.add(jMIGerenciarUsu);

        jMenuBar1.add(jMUsuarios);

        jMFornecedores.setText("Fornecedores");

        jMIGerenciarForne.setText("Gerenciar Fornecedores");
        jMIGerenciarForne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciarForneActionPerformed(evt);
            }
        });
        jMFornecedores.add(jMIGerenciarForne);

        jMenuBar1.add(jMFornecedores);

        jMProdutos.setText("Produtos");

        jMIGerenciarProd.setText("Gerenciar Produtos");
        jMIGerenciarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciarProdActionPerformed(evt);
            }
        });
        jMProdutos.add(jMIGerenciarProd);

        jMenuBar1.add(jMProdutos);

        jMVendas.setText("Vendas");

        jMIEfeVenda.setText("Efetuar Venda");
        jMIEfeVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEfeVendaActionPerformed(evt);
            }
        });
        jMVendas.add(jMIEfeVenda);

        jMenuBar1.add(jMVendas);

        jMRelatorio.setText("Relatório");

        jMIRelatorioProd.setText("Produtos");
        jMIRelatorioProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioProdActionPerformed(evt);
            }
        });
        jMRelatorio.add(jMIRelatorioProd);

        jMIRelatVendas.setText("Vendas");
        jMIRelatVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatVendasActionPerformed(evt);
            }
        });
        jMRelatorio.add(jMIRelatVendas);

        jMenuBar1.add(jMRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean validarAdm(int cod){
        cod = codLogin;
        
        if (CadastrarFuncionario.cadastrarUsuario.get(cod).getPerm().equals("Administrador")) {
            return true;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para acessar essa tela!");
            return false;
        }
    }
    private void jMIGerenciarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciarProdActionPerformed
        for (int i = 0; i < CadastrarFuncionario.cadastrarUsuario.size(); i++) {
            if (validarAdm(codLogin)) {
                CadastroProduto cadastroProduto = new CadastroProduto();
                cadastroProduto.setVisible(true);
                break;
            } else {
                CadastroProduto cadastroProduto = new CadastroProduto();
                cadastroProduto.setVisible(false);
                break;
            }
        }
    }//GEN-LAST:event_jMIGerenciarProdActionPerformed

    private void jMIGerenciarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciarUsuActionPerformed
        for (int i = 0; i < CadastrarFuncionario.cadastrarUsuario.size(); i++) {
            if (validarAdm(codLogin)) {
                CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
                cadastroFuncionario.setVisible(true);
                break;
            } else {
                CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
                cadastroFuncionario.setVisible(false);
                break;
            }
        }

    }//GEN-LAST:event_jMIGerenciarUsuActionPerformed

    private void jMIGerenciarForneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciarForneActionPerformed
        for (int i = 0; i < CadastrarFuncionario.cadastrarUsuario.size(); i++) {
            if (validarAdm(codLogin)) {
                CadastroFornecedores cadastroFornecedores = new CadastroFornecedores();
                cadastroFornecedores.setVisible(true);
                break;
            } else {
                CadastroFornecedores cadastroFornecedores = new CadastroFornecedores();
                cadastroFornecedores.setVisible(false);
                break;
            }
        }
    }//GEN-LAST:event_jMIGerenciarForneActionPerformed

    private void jMIEfeVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEfeVendaActionPerformed
        VenderProduto retirarProduto = new VenderProduto();
        retirarProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMIEfeVendaActionPerformed

    private void jMIRelatorioProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioProdActionPerformed
        for (int i = 0; i < CadastrarFuncionario.cadastrarUsuario.size(); i++) {
            if (validarAdm(codLogin)) {

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMIRelatorioProdActionPerformed

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMIPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPerfilActionPerformed
        
        Perfil perfil = new Perfil(codLogin);
        perfil.setVisible(true);
    }//GEN-LAST:event_jMIPerfilActionPerformed

    private void jMIRelatVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatVendasActionPerformed
        for (int i = 0; i < CadastrarFuncionario.cadastrarUsuario.size(); i++) {
            if (validarAdm(codLogin)) {
                RelatorioVendas relatorioVendas = new RelatorioVendas();
                relatorioVendas.setVisible(true);
                break;
            } else {
                RelatorioVendas relatorioVendas = new RelatorioVendas();
                relatorioVendas.setVisible(false);
                break;
            }
        }
    }//GEN-LAST:event_jMIRelatVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMArquivos;
    private javax.swing.JMenu jMFornecedores;
    private javax.swing.JMenuItem jMIEfeVenda;
    private javax.swing.JMenuItem jMIGerenciarForne;
    private javax.swing.JMenuItem jMIGerenciarProd;
    private javax.swing.JMenuItem jMIGerenciarUsu;
    private javax.swing.JMenuItem jMIPerfil;
    private javax.swing.JMenuItem jMIRelatVendas;
    private javax.swing.JMenuItem jMIRelatorioProd;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenu jMProdutos;
    private javax.swing.JMenu jMRelatorio;
    private javax.swing.JMenu jMUsuarios;
    private javax.swing.JMenu jMVendas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
