/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Relatorios;

import classes.CadastrarProduto;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz
 */
public class RelatorioProdutos extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioVendas
     */
    public RelatorioProdutos() {
        initComponents();
        jBGerarRela.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBQtdCaProduAno = new javax.swing.JCheckBox();
        jCheckBQtdCaProdMes = new javax.swing.JCheckBox();
        jBGerarRela = new javax.swing.JButton();
        jBProcurarDiretorio = new javax.swing.JButton();
        txtCaminho = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório de Vendas"));

        jCheckBQtdCaProduAno.setText("Quantidade de produtos cadastrados no ano");

        jCheckBQtdCaProdMes.setText(" Quantidade de produtos cadastrados no mês");

        jBGerarRela.setBackground(new java.awt.Color(255, 51, 102));
        jBGerarRela.setText("Gerar Relatório");
        jBGerarRela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarRelaActionPerformed(evt);
            }
        });

        jBProcurarDiretorio.setBackground(new java.awt.Color(255, 51, 153));
        jBProcurarDiretorio.setText("Procurar Diretorio");
        jBProcurarDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcurarDiretorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBQtdCaProduAno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBQtdCaProdMes)
                        .addContainerGap(10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBGerarRela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCaminho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBProcurarDiretorio)))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jCheckBQtdCaProdMes)
                .addGap(18, 18, 18)
                .addComponent(jCheckBQtdCaProduAno)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBProcurarDiretorio)
                    .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBGerarRela)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBGerarRelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarRelaActionPerformed
        Document documentPDF = new Document();

        String[] codi = new String[CadastrarProduto.cadastrarProduto.size()];
        String[] nomePro = new String[CadastrarProduto.cadastrarProduto.size()];
        String[] quantidade = new String[CadastrarProduto.cadastrarProduto.size()];
        String[] mesDoCadastro = new String[CadastrarProduto.cadastrarProduto.size()];
        String[] anoDoCadastro = new String[CadastrarProduto.cadastrarProduto.size()];
        String[] totalGasto = new String[CadastrarProduto.cadastrarProduto.size()];
        
        PdfPTable tableCa = new PdfPTable(6);
        PdfPTable[] table = new PdfPTable[(6)];
        
        Font fonte = new Font(Font.FontFamily.TIMES_ROMAN, 20, Font.BOLD);
        Font fonteT = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);
        
        PdfPCell[] codC = new PdfPCell[CadastrarProduto.cadastrarProduto.size()];
        PdfPCell[] nomeC = new PdfPCell[CadastrarProduto.cadastrarProduto.size()];
        PdfPCell[] qtdC = new PdfPCell[CadastrarProduto.cadastrarProduto.size()];
        PdfPCell[] mesCadastroC = new PdfPCell[CadastrarProduto.cadastrarProduto.size()];
        PdfPCell[] anoCadastroC = new PdfPCell[CadastrarProduto.cadastrarProduto.size()];
        PdfPCell[] totalGastoC = new PdfPCell[CadastrarProduto.cadastrarProduto.size()];
        
        try {
            PdfWriter.getInstance(documentPDF, new FileOutputStream(txtCaminho.getText() + "//Relatório de produtos.pdf"));

            documentPDF.open();
            documentPDF.newPage();
            documentPDF.setPageSize(PageSize.A4);

            fonteT.setColor(BaseColor.WHITE);

            Paragraph cab = new Paragraph("\n RELATÓRIO DE PRODUTOS ", fonte);

            cab.setAlignment(Element.ALIGN_CENTER);

            documentPDF.add(cab);
            documentPDF.add(new Paragraph("\n"));
            documentPDF.add(new Paragraph("\n"));
            documentPDF.add(new Paragraph("\n"));

            for (int i = 0; i < CadastrarProduto.cadastrarProduto.size(); i++) {
                codi[i] = String.valueOf(CadastrarProduto.cadastrarProduto.get(i).getCodproduto());
                nomePro[i] = CadastrarProduto.cadastrarProduto.get(i).getNome();
                quantidade[i] = String.valueOf(CadastrarProduto.cadastrarProduto.get(i).getQuantidade());
                mesDoCadastro[i] = String.valueOf(CadastrarProduto.cadastrarProduto.get(i).getMesCadastro());
                anoDoCadastro[i] = String.valueOf(CadastrarProduto.cadastrarProduto.get(i).getAnoCadastro());
                totalGasto[i] = String.valueOf(CadastrarProduto.cadastrarProduto.get(i).getTotalGasto());

                codC[i] = new PdfPCell(new Paragraph(codi[i]));
                nomeC[i] = new PdfPCell(new Paragraph(nomePro[i]));
                qtdC[i] = new PdfPCell(new Paragraph(quantidade[i]));
                mesCadastroC[i] = new PdfPCell(new Paragraph(mesDoCadastro[i]));
                anoCadastroC[i] = new PdfPCell(new Paragraph(anoDoCadastro[i]));
                totalGastoC[i] = new PdfPCell(new Paragraph(totalGasto[i]));
                
                PdfPCell cod = new PdfPCell(new Paragraph("Código", fonteT));
                PdfPCell nome = new PdfPCell(new Paragraph("Nome", fonteT));
                PdfPCell qtd = new PdfPCell(new Paragraph("Quantidade", fonteT));
                PdfPCell mesCompra = new PdfPCell(new Paragraph("Mês compra", fonteT));
                PdfPCell anoCompra = new PdfPCell(new Paragraph("Ano compra", fonteT));
                PdfPCell totalGas = new PdfPCell(new Paragraph("Total gasto", fonteT));
                
                cod.setBackgroundColor(BaseColor.BLACK);
                nome.setBackgroundColor(BaseColor.BLACK);
                qtd.setBackgroundColor(BaseColor.BLACK);
                mesCompra.setBackgroundColor(BaseColor.BLACK);
                anoCompra.setBackgroundColor(BaseColor.BLACK);
                totalGas.setBackgroundColor(BaseColor.BLACK);

                if ((jCheckBQtdCaProduAno.isSelected()) && (jCheckBQtdCaProdMes.isSelected())) {
                    tableCa = new PdfPTable(6);
                    table[i] = new PdfPTable(6);
                    
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(mesCompra);
                    tableCa.addCell(anoCompra);
                    tableCa.addCell(totalGas);
                    
                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(mesCadastroC[i]);
                    table[i].addCell(anoCadastroC[i]);
                    table[i].addCell(totalGastoC[i]);

                } else if (jCheckBQtdCaProduAno.isSelected()) {
                    tableCa = new PdfPTable(4);
                    table[i] = new PdfPTable(4);
    
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(anoCompra);

                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(anoCadastroC[i]);

                } else if (jCheckBQtdCaProdMes.isSelected()) {
                    tableCa = new PdfPTable(4);
                    table[i] = new PdfPTable(4);
                    
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(mesCompra);

                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(mesCadastroC[i]);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Nenhum tipo de relatório selecionado");
                }
            }

            documentPDF.add(tableCa);

            for (int i = 0; i < CadastrarProduto.cadastrarProduto.size(); i++) {
                documentPDF.add(table[i]);
            }

        } catch (DocumentException de) {
            de.printStackTrace();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } finally {
            documentPDF.close();
            JOptionPane.showMessageDialog(null, "Relatório gerado com sucesso!");
        }

    }//GEN-LAST:event_jBGerarRelaActionPerformed

    private void jBProcurarDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcurarDiretorioActionPerformed
        jBGerarRela.setEnabled(true);
        JFileChooser local = new JFileChooser();
        local.setDialogTitle("Selecione a pasta");
        local.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int opcao = local.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            File file = new File("caminho");
            file = local.getSelectedFile();
            String caminho = file.getAbsolutePath();
            txtCaminho.setText(caminho);
        }
    }//GEN-LAST:event_jBProcurarDiretorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGerarRela;
    private javax.swing.JButton jBProcurarDiretorio;
    private javax.swing.JCheckBox jCheckBQtdCaProdMes;
    private javax.swing.JCheckBox jCheckBQtdCaProduAno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
}
