/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Relatorios;

import classes.Vendas;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author luiz
 */
public class RelatorioVendas extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioVendas
     */
    public RelatorioVendas() {
        initComponents();
        jBGerarRela.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBLucroVendas = new javax.swing.JCheckBox();
        jCheckBQtdVendasAno = new javax.swing.JCheckBox();
        jCheckBQtdVendasMes = new javax.swing.JCheckBox();
        jBGerarRela = new javax.swing.JButton();
        jBProcurarDiretorio = new javax.swing.JButton();
        txtCaminho = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório de Vendas"));

        jCheckBLucroVendas.setText("Lucro de vendas");

        jCheckBQtdVendasAno.setText("Quantidade de produtos vendidos no ano");

        jCheckBQtdVendasMes.setText(" Quantidade de produtos vendidos no mês");

        jBGerarRela.setBackground(new java.awt.Color(255, 51, 102));
        jBGerarRela.setText("Gerar Relatório");
        jBGerarRela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarRelaActionPerformed(evt);
            }
        });

        jBProcurarDiretorio.setBackground(new java.awt.Color(255, 51, 153));
        jBProcurarDiretorio.setText("Procurar Diretorio");
        jBProcurarDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcurarDiretorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBQtdVendasMes)
                            .addComponent(jCheckBQtdVendasAno)
                            .addComponent(jCheckBLucroVendas))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBGerarRela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCaminho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBProcurarDiretorio)))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jCheckBLucroVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBQtdVendasAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBQtdVendasMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBProcurarDiretorio)
                    .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBGerarRela)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBGerarRelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarRelaActionPerformed
        Document documentPDF = new Document();

        String[] codiVenda = new String[Vendas.vendas.size()];
        String[] codi = new String[Vendas.vendas.size()];
        String[] nomePro = new String[Vendas.vendas.size()];
        String[] quantidade = new String[Vendas.vendas.size()];
        String[] valorVenda = new String[Vendas.vendas.size()];
        String[] mesDaVenda = new String[Vendas.vendas.size()];
        String[] anoDaVenda = new String[Vendas.vendas.size()];
        String[] valorGasto = new String[Vendas.vendas.size()];
        String[] lucro = new String[Vendas.vendas.size()];

        PdfPTable tableCa = new PdfPTable(9);
        PdfPTable[] table = new PdfPTable[(9)];

        Font fonte = new Font(Font.FontFamily.TIMES_ROMAN, 20, Font.BOLD);
        Font fonteT = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

        PdfPCell[] codVendaC = new PdfPCell[Vendas.vendas.size()];
        PdfPCell[] codC = new PdfPCell[Vendas.vendas.size()];
        PdfPCell[] nomeC = new PdfPCell[Vendas.vendas.size()];
        PdfPCell[] qtdC = new PdfPCell[Vendas.vendas.size()];
        PdfPCell[] valorC = new PdfPCell[Vendas.vendas.size()];
        PdfPCell[] mesVendaC = new PdfPCell[Vendas.vendas.size()];
        PdfPCell[] anoVendaC = new PdfPCell[Vendas.vendas.size()];
        PdfPCell[] valorGastoC = new PdfPCell[Vendas.vendas.size()];
        PdfPCell[] lucrovendasC = new PdfPCell[Vendas.vendas.size()];

        try {
            PdfWriter.getInstance(documentPDF, new FileOutputStream(txtCaminho.getText() + "//Relatório de vendas.pdf"));

            documentPDF.open();
            documentPDF.newPage();
            documentPDF.setPageSize(PageSize.A4);

            fonteT.setColor(BaseColor.WHITE);

            Paragraph cab = new Paragraph("\n RELATÓRIO DE VENDAS ", fonte);

            cab.setAlignment(Element.ALIGN_CENTER);

            documentPDF.add(cab);
            documentPDF.add(new Paragraph("\n"));
            documentPDF.add(new Paragraph("\n"));
            documentPDF.add(new Paragraph("\n"));

            for (int i = 0; i < Vendas.vendas.size(); i++) {
                table[i] = new PdfPTable(8);
                tableCa = new PdfPTable(8);

                codiVenda[i] = String.valueOf(Vendas.vendas.get(i).getCodVenda());
                codi[i] = String.valueOf(Vendas.vendas.get(i).getCodProdutoVendido());
                nomePro[i] = Vendas.vendas.get(i).getNome();
                quantidade[i] = String.valueOf(Vendas.vendas.get(i).getQuantidade());
                valorVenda[i] = String.valueOf(Vendas.vendas.get(i).getValorVenda());
                mesDaVenda[i] = String.valueOf(Vendas.vendas.get(i).getMes());
                anoDaVenda[i] = String.valueOf(Vendas.vendas.get(i).getAno());
                valorGasto[i] = String.valueOf(Vendas.vendas.get(i).getValorGasto());
                lucro[i] = String.valueOf(Vendas.vendas.get(i).getLucro());

                codVendaC[i] = new PdfPCell(new Paragraph(codiVenda[i]));
                codC[i] = new PdfPCell(new Paragraph(codi[i]));
                nomeC[i] = new PdfPCell(new Paragraph(nomePro[i]));
                qtdC[i] = new PdfPCell(new Paragraph(quantidade[i]));
                valorC[i] = new PdfPCell(new Paragraph(valorVenda[i]));
                mesVendaC[i] = new PdfPCell(new Paragraph(mesDaVenda[i]));
                anoVendaC[i] = new PdfPCell(new Paragraph(anoDaVenda[i]));
                valorGastoC[i] = new PdfPCell(new Paragraph(valorGasto[i]));
                lucrovendasC[i] = new PdfPCell(new Paragraph(lucro[i]));

                PdfPCell codVenda = new PdfPCell(new Paragraph("Código Venda", fonteT));
                PdfPCell cod = new PdfPCell(new Paragraph("Código Produto", fonteT));
                PdfPCell nome = new PdfPCell(new Paragraph("Nome Produto", fonteT));
                PdfPCell qtd = new PdfPCell(new Paragraph("Quantidade", fonteT));
                PdfPCell valor = new PdfPCell(new Paragraph("Valor venda", fonteT));
                PdfPCell mesVenda = new PdfPCell(new Paragraph("Mês venda", fonteT));
                PdfPCell anoVenda = new PdfPCell(new Paragraph("Ano venda", fonteT));
                PdfPCell valorGas = new PdfPCell(new Paragraph("Valor gasto", fonteT));
                PdfPCell lucrovendas = new PdfPCell(new Paragraph("Lucro de Vendas", fonteT));

                codVenda.setBackgroundColor(BaseColor.BLACK);
                cod.setBackgroundColor(BaseColor.BLACK);
                nome.setBackgroundColor(BaseColor.BLACK);
                qtd.setBackgroundColor(BaseColor.BLACK);
                valor.setBackgroundColor(BaseColor.BLACK);
                mesVenda.setBackgroundColor(BaseColor.BLACK);
                anoVenda.setBackgroundColor(BaseColor.BLACK);
                valorGas.setBackgroundColor(BaseColor.BLACK);
                lucrovendas.setBackgroundColor(BaseColor.BLACK);

                if ((jCheckBLucroVendas.isSelected()) && (jCheckBQtdVendasAno.isSelected()) && (jCheckBQtdVendasMes.isSelected())) {
                    table[i] = new PdfPTable(8);
                    tableCa = new PdfPTable(8);

                    tableCa.addCell(codVenda);
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(valor);
                    tableCa.addCell(mesVenda);
                    tableCa.addCell(anoVenda);
                    tableCa.addCell(valorGas);
                    tableCa.addCell(lucrovendas);

                    table[i].addCell(codVendaC[i]);
                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(valorC[i]);
                    table[i].addCell(mesVendaC[i]);
                    table[i].addCell(anoVendaC[i]);
                    table[i].addCell(valorGastoC[i]);
                    table[i].addCell(lucrovendasC[i]);

                } else if ((jCheckBLucroVendas.isSelected()) && (jCheckBQtdVendasAno.isSelected())) {
                    table[i] = new PdfPTable(7);
                    tableCa = new PdfPTable(7);

                    tableCa.addCell(codVenda);
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(valor);
                    tableCa.addCell(anoVenda);
                    tableCa.addCell(lucrovendas);

                    table[i].addCell(codVendaC[i]);
                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(valorC[i]);
                    table[i].addCell(anoVendaC[i]);
                    table[i].addCell(lucrovendasC[i]);

                } else if ((jCheckBLucroVendas.isSelected()) && (jCheckBQtdVendasMes.isSelected())) {
                    table[i] = new PdfPTable(7);
                    tableCa = new PdfPTable(7);

                    tableCa.addCell(codVenda);
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(valor);
                    tableCa.addCell(mesVenda);
                    tableCa.addCell(lucrovendas);

                    table[i].addCell(codVendaC[i]);
                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(valorC[i]);
                    table[i].addCell(mesVendaC[i]);
                    table[i].addCell(lucrovendasC[i]);

                } else if ((jCheckBQtdVendasAno.isSelected()) && (jCheckBQtdVendasMes.isSelected())) {
                    table[i] = new PdfPTable(5);
                    tableCa = new PdfPTable(5);

                    tableCa.addCell(codVenda);
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(mesVenda);

                    table[i].addCell(codVendaC[i]);
                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(mesVendaC[i]);

                } else if (jCheckBLucroVendas.isSelected()) {
                    table[i] = new PdfPTable(2);
                    tableCa = new PdfPTable(2);

                    tableCa.addCell(codVenda);
                    tableCa.addCell(lucrovendas);

                    table[i].addCell(codVendaC[i]);
                    table[i].addCell(lucrovendasC[i]);

                } else if (jCheckBQtdVendasAno.isSelected()) {
                    table[i] = new PdfPTable(5);
                    tableCa = new PdfPTable(5);

                    tableCa.addCell(codVenda);
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(mesVenda);

                    table[i].addCell(codVendaC[i]);
                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(mesVendaC[i]);

                } else if (jCheckBQtdVendasMes.isSelected()) {
                    table[i] = new PdfPTable(5);
                    tableCa = new PdfPTable(5);

                    tableCa.addCell(codVenda);
                    tableCa.addCell(cod);
                    tableCa.addCell(nome);
                    tableCa.addCell(qtd);
                    tableCa.addCell(anoVenda);

                    table[i].addCell(codVendaC[i]);
                    table[i].addCell(codC[i]);
                    table[i].addCell(nomeC[i]);
                    table[i].addCell(qtdC[i]);
                    table[i].addCell(anoVendaC[i]);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Nenhum tipo de relatório selecionado");
                }
            }

            documentPDF.add(tableCa);

            for (int i = 0; i < Vendas.vendas.size(); i++) {
                documentPDF.add(table[i]);
            }

        } catch (DocumentException de) {
            de.printStackTrace();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } finally {
            documentPDF.close();
            JOptionPane.showMessageDialog(null, "Relatório gerado com sucesso!");
        }

    }//GEN-LAST:event_jBGerarRelaActionPerformed

    private void jBProcurarDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcurarDiretorioActionPerformed
        jBGerarRela.setEnabled(true);
        JFileChooser local = new JFileChooser();
        local.setDialogTitle("Selecione a pasta");
        local.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int opcao = local.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            File file = new File("caminho");
            file = local.getSelectedFile();
            String caminho = file.getAbsolutePath();
            txtCaminho.setText(caminho);
        }
    }//GEN-LAST:event_jBProcurarDiretorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGerarRela;
    private javax.swing.JButton jBProcurarDiretorio;
    private javax.swing.JCheckBox jCheckBLucroVendas;
    private javax.swing.JCheckBox jCheckBQtdVendasAno;
    private javax.swing.JCheckBox jCheckBQtdVendasMes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
}
